using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GasStationApp.Migrations
{
    /// <inheritdoc />
    public partial class Phase1SecurityAndTrust : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Identity Tables (These might not exist yet if you just added Identity)
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetRoles\" ( \"Id\" text NOT NULL, \"Name\" character varying(256), \"NormalizedName\" character varying(256), \"ConcurrencyStamp\" text, CONSTRAINT \"PK_AspNetRoles\" PRIMARY KEY (\"Id\") );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetUsers\" ( \"Id\" text NOT NULL, \"UserName\" character varying(256), \"NormalizedUserName\" character varying(256), \"Email\" character varying(256), \"NormalizedEmail\" character varying(256), \"EmailConfirmed\" boolean NOT NULL, \"PasswordHash\" text, \"SecurityStamp\" text, \"ConcurrencyStamp\" text, \"PhoneNumber\" text, \"PhoneNumberConfirmed\" boolean NOT NULL, \"TwoFactorEnabled\" boolean NOT NULL, \"LockoutEnd\" timestamp with time zone, \"LockoutEnabled\" boolean NOT NULL, \"AccessFailedCount\" integer NOT NULL, CONSTRAINT \"PK_AspNetUsers\" PRIMARY KEY (\"Id\") );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetRoleClaims\" ( \"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"RoleId\" text NOT NULL, \"ClaimType\" text, \"ClaimValue\" text, CONSTRAINT \"PK_AspNetRoleClaims\" PRIMARY KEY (\"Id\"), CONSTRAINT \"FK_AspNetRoleClaims_AspNetRoles_RoleId\" FOREIGN KEY (\"RoleId\") REFERENCES \"AspNetRoles\" (\"Id\") ON DELETE CASCADE );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetUserClaims\" ( \"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"UserId\" text NOT NULL, \"ClaimType\" text, \"ClaimValue\" text, CONSTRAINT \"PK_AspNetUserClaims\" PRIMARY KEY (\"Id\"), CONSTRAINT \"FK_AspNetUserClaims_AspNetUsers_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetUserLogins\" ( \"LoginProvider\" text NOT NULL, \"ProviderKey\" text NOT NULL, \"ProviderDisplayName\" text, \"UserId\" text NOT NULL, CONSTRAINT \"PK_AspNetUserLogins\" PRIMARY KEY (\"LoginProvider\", \"ProviderKey\"), CONSTRAINT \"FK_AspNetUserLogins_AspNetUsers_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetUserRoles\" ( \"UserId\" text NOT NULL, \"RoleId\" text NOT NULL, CONSTRAINT \"PK_AspNetUserRoles\" PRIMARY KEY (\"UserId\", \"RoleId\"), CONSTRAINT \"FK_AspNetUserRoles_AspNetRoles_RoleId\" FOREIGN KEY (\"RoleId\") REFERENCES \"AspNetRoles\" (\"Id\") ON DELETE CASCADE, CONSTRAINT \"FK_AspNetUserRoles_AspNetUsers_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE );");
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AspNetUserTokens\" ( \"UserId\" text NOT NULL, \"LoginProvider\" text NOT NULL, \"Name\" text NOT NULL, \"Value\" text, CONSTRAINT \"PK_AspNetUserTokens\" PRIMARY KEY (\"UserId\", \"LoginProvider\", \"Name\"), CONSTRAINT \"FK_AspNetUserTokens_AspNetUsers_UserId\" FOREIGN KEY (\"UserId\") REFERENCES \"AspNetUsers\" (\"Id\") ON DELETE CASCADE );");

            // Update reports table with new columns if they don't exist
            migrationBuilder.Sql("ALTER TABLE reports ADD COLUMN IF NOT EXISTS upvotes integer DEFAULT 0;");
            migrationBuilder.Sql("ALTER TABLE reports ADD COLUMN IF NOT EXISTS downvotes integer DEFAULT 0;");
            migrationBuilder.Sql("ALTER TABLE reports ADD COLUMN IF NOT EXISTS is_hidden boolean DEFAULT false;");

            // Create report_votes table
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS report_votes ( id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, report_id bigint NOT NULL REFERENCES reports(id) ON DELETE CASCADE, user_id text, is_upvote boolean NOT NULL );");

            // Indices
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_AspNetRoleClaims_RoleId\" ON \"AspNetRoleClaims\" (\"RoleId\");");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"RoleNameIndex\" ON \"AspNetRoles\" (\"NormalizedName\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_AspNetUserClaims_UserId\" ON \"AspNetUserClaims\" (\"UserId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_AspNetUserLogins_UserId\" ON \"AspNetUserLogins\" (\"UserId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_AspNetUserRoles_RoleId\" ON \"AspNetUserRoles\" (\"RoleId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"EmailIndex\" ON \"AspNetUsers\" (\"NormalizedEmail\");");
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"UserNameIndex\" ON \"AspNetUsers\" (\"NormalizedUserName\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_report_votes_report_id\" ON report_votes (report_id);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Handled carefully as this is a non-destructive manual fixup
        }
    }
}